# Generated by Django 5.0.4 on 2024-04-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peeps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField(blank=True)),
                ('event', models.CharField(blank=True, max_length=256)),
                ('notes', models.TextField(blank=True, max_length=512)),
            ],
        ),
    ]
