# Generated by Django 5.0.4 on 2024-04-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeps', '0002_alter_peeps_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peeps',
            new_name='Nompeeps',
        ),
    ]
