# Generated by Django 5.0.4 on 2024-04-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeps', '0003_rename_peeps_nompeeps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nompeeps',
            new_name='Nompeep',
        ),
    ]
