# Generated by Django 5.0.4 on 2024-04-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeps', '0005_alter_nompeep_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thatdate', models.DateField()),
                ('place', models.CharField(max_length=128)),
                ('mentalnote', models.TextField(max_length=512)),
                ('peeps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peeps.nompeep')),
            ],
        ),
    ]
