# Generated by Django 5.0.4 on 2024-04-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeps', '0006_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='peeps',
            new_name='nompeep',
        ),
    ]
