# Generated by Django 5.0.4 on 2024-04-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeps', '0007_rename_peeps_reminder_nompeep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('text_color', models.CharField(default='black', max_length=16)),
                ('bg_color', models.CharField(default='yellow', max_length=16)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-thatdate']},
        ),
        migrations.AlterField(
            model_name='reminder',
            name='mentalnote',
            field=models.TextField(max_length=512, verbose_name='Mental note'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='thatdate',
            field=models.DateField(verbose_name='Reminder date'),
        ),
    ]
