# Generated by Django 5.0.4 on 2024-04-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeps', '0008_group_alter_reminder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='nompeep',
            name='groups',
            field=models.ManyToManyField(to='peeps.group'),
        ),
    ]
